version: 3.0.{build}
skip_tags: true
skip_branch_with_pr: true
skip_commits:
    message: /(Create|Update).*\.(png|jpg|jpeg|bmp|gif|md)/
branches:
    only:
    - master
environment:
    nodejs_version: 14.3.0
install:
- ps: Install-Product node $env:nodejs_version
- ps: >- 
    npm install --loglevel=error

    "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII

build_script:
- mkdir -p dist
- copy package.json dist\
- copy data\bancos.json dist\
- cd dist
- git config user.email "build@appveyor.com"
- git config user.name "AppVeyor"
- npm version %APPVEYOR_BUILD_VERSION% -m 'v%APPVEYOR_BUILD_VERSION%'
- npm publish