version: 2.0.{build}
skip_commits:
    message: /(Create|Update).*\.(png|jpg|jpeg|bmp|gif|md)/
branches:
    only:
    - master
environment:
    nodejs_version: 6
install:
- ps: Install-Product node $env:nodejs_version
- ps: >- 
    npm install --loglevel=error

    "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII

build_script:
- git config user.email "build@appveyor.com"
- git config user.name "AppVeyor"
- npm version %APPVEYOR_BUILD_VERSION% -m 'v%APPVEYOR_BUILD_VERSION%'
- npm publish